package com.jk.bean;
// Generated 2018-4-9 14:44:24 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TShopdalei generated by hbm2java
 */
@Entity
@Table(name = "t_shopdalei")
public class TShopdalei implements java.io.Serializable {

	private Integer id;
	private String name;
	private String notes;

	public TShopdalei() {
	}

	public TShopdalei(String name, String notes) {
		this.name = name;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "notes")
	public String getnotes() {
		return this.notes;
	}

	public void setnotes(String notes) {
		this.notes = notes;
	}

	/* (non-Javadoc)    
	 * @see java.lang.Object#toString()    
	 */
	@Override
	public String toString() {
		return "TShopdalei [id=" + id + ", name=" + name + ", notes=" + notes + "]";
	}

}
